"""empty message

Revision ID: 68dbf085d0c9
Revises: 137312ebb88b
Create Date: 2020-04-07 15:25:30.701392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68dbf085d0c9'
down_revision = '137312ebb88b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('problem', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'problem')
    # ### end Alembic commands ###
